### ISSUE TITLE
Xnahia l idea li hate5edmo 3liha

### ISSUE THREAD

**Issue by ziadab** [moroccanprogrammers/aji_taftar_mobile#1]
Xi wa7de ygol l'idea li hate5edmo 3liha and wax makaynax start dial lcode
and 7aja 5era madertox sketch dial design dial l app ??

**Comment by anas3636** [comment]
C'est quoi les fonctionnalités  qu'on veux avoir dans l'appli ?

**Comment by aminekarimii** [comment]
App native wla hybrid ?

**Comment by MourahiMouaad** [comment]
ba9i ma7edednach ntsnaw bima tjem3o drari

**Comment by ziadab** [comment]
@MOUAAD8MOURAHI Bda men db bax jaw le5erin nkmlo

**Comment by NaoualSmaili** [comment]
ba9i ma t lança l cahier des charges
